$(document).ready(function(){
  $(".ht_searchBox_main").hide();
  $("#btn_tour").click(function(){
    $(".ht_searchBox_main").hide();
    $("#ht_search_tour").show();
  });
  $("#btn_hotel").click(function(){
    $(".ht_searchBox_main").hide();
    $("#ht_search_hotel").show();
  });
  $("#btn_ticket").click(function(){
    $(".ht_searchBox_main").hide();
    $("#ht_search_ticket").show();
  });
});
